spring:
  application:
    name: "email-sender"
  output:
    ansi:
      enabled: always
server:
  port: 8081
  error:
    include-stacktrace: never
    include-message: never
management:
  endpoints:
    web:
      exposure:
        include: info, metrics, health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Endereço do Eureka Server
  instance:
    prefer-ip-address: true # Configuração opcional, usa o IP no lugar do hostname