scrape_configs:
#  - job_name: "prometheus"
#    scrape_interval: 5s
#    static_configs:
#      - targets: [ "localhost:9090" ]

  - job_name: "email-sender"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 2s
    static_configs:
      - targets: [ "host.docker.internal:8080" ]
        labels:
          application: "email-sender"